# Generated by Django 5.0.3 on 2024-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
